[global]

# Run as a boundary clock
clock_type              BC

# Each NIC may have its own PHC
boundary_clock_jbod     1

# Hardware timestamping
time_stamping           hardware

# Ouster uses UDP PTP
network_transport       UDPv4

# Start with standard E2E delay mechanism
delay_mechanism         E2E

# PTP domain
domainNumber            0

# Logging
verbose                 1
summary_interval        1

# Don't allow the PC to win BMCA against the Ouster
priority1               200
priority2               200


[enp1s0]

# Ouster-facing interface
clientOnly              1


[enp2s0]

# Camera 1-facing interface
serverOnly              1


[enp3s0]

# Camera 2-facing interface
serverOnly              1


[enp4s0]

# Camera 3-facing interface
serverOnly              1


[enp5s0]

# Camera 4-facing interface
serverOnly              1