# enp2s0 = GNSS
# enp3s0 = Ouster
# enp5s0 = CAM 1 Left-Stereo
# enp6s0 = CAM 2 Right-Stereo
# enp7s0 = CAM 3
# enp8s0 = CAM 4

[global]

boundary_clock_jbod     1

time_stamping           hardware
network_transport       UDPv4
delay_mechanism         E2E

domainNumber            0

verbose                 1
summary_interval        1

priority1               128
priority2               128

ptp_minor_version 0

# [enp2s0]
# GNSS

[enp3s0]
# Ouster

[enp5s0]
# Camera 1

[enp6s0]
# Camera 2

[enp7s0]
# Camera 3

[enp8s0]
# Camera 4
