# enpXs0 = GNSS
# enp3s0 = Ouster
# enp5s0 = CAM 1 Left-Stereo
# enp6s0 = CAM 2 Right-Stereo
# enp7s0 = CAM 3
# enp8s0 = CAM 4

[global]

clock_type              BC
boundary_clock_jbod     1

time_stamping           hardware
network_transport       UDPv4
delay_mechanism         E2E

domainNumber            0

verbose                 1
summary_interval        1

priority1               128
priority2               128
#clientOnly 				1 ?


# [enpXs0]
# GNSS
# serverOnly 0

#[enp3s0]
# Ouster
#serverOnly 1

[enp5s0]
# Camera 1 (Set Basler as a grand master until we have the GNSS)
serverOnly 0

[enp6s0]
# Camera 2
serverOnly 1

[enp7s0]
# Camera 3
serverOnly 1

[enp8s0]
# Camera 4
serverOnly 1
